// <auto-generated />
using System;
using ERP_BIEN.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP_BIEN.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427092407_permisos")]
    partial class permisos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP_BIEN.Models.Ascendant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disability")
                        .HasColumnType("bit");

                    b.Property<int?>("PersonalInformationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonalInformationId");

                    b.ToTable("Ascendants");
                });

            modelBuilder.Entity("ERP_BIEN.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ERP_BIEN.Models.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disability")
                        .HasColumnType("bit");

                    b.Property<int?>("PersonalInformationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonalInformationId");

                    b.ToTable("Childs");
                });

            modelBuilder.Entity("ERP_BIEN.Models.CompanyInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AplicableWorkCalendar")
                        .HasColumnType("bit");

                    b.Property<double>("Bonus")
                        .HasColumnType("float");

                    b.Property<bool>("Car")
                        .HasColumnType("bit");

                    b.Property<bool>("CasqueDor")
                        .HasColumnType("bit");

                    b.Property<int>("Contract")
                        .HasColumnType("int");

                    b.Property<string>("ContractCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ContractStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContratEndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DailySchedule")
                        .HasColumnType("bit");

                    b.Property<double>("DaosHourlyCosts")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DateConversionUnlimitedContract")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateNewTypeProfile")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DirectionAttach")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EndDateTrialPeriod")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Executive")
                        .HasColumnType("bit");

                    b.Property<bool>("ExpensesTeleworking")
                        .HasColumnType("bit");

                    b.Property<bool>("FunctionalComplement")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<bool>("MedicalInsurance")
                        .HasColumnType("bit");

                    b.Property<int>("NewTypeProfile")
                        .HasColumnType("int");

                    b.Property<double>("PotencialBonus")
                        .HasColumnType("float");

                    b.Property<int>("Presence")
                        .HasColumnType("int");

                    b.Property<string>("SectorOfActivity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Seniority")
                        .HasColumnType("float");

                    b.Property<int>("TypeProfile")
                        .HasColumnType("int");

                    b.Property<bool>("WorkShifts")
                        .HasColumnType("bit");

                    b.Property<double>("YearlyGrossSalaryFT")
                        .HasColumnType("float");

                    b.Property<double>("YearlyGrossSalaryPT")
                        .HasColumnType("float");

                    b.Property<int>("office")
                        .HasColumnType("int");

                    b.Property<int>("spotNumber")
                        .HasColumnType("int");

                    b.Property<int>("technicalCenter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CompanyInformation");
                });

            modelBuilder.Entity("ERP_BIEN.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ManufacturingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumberOfDevice")
                        .HasColumnType("int");

                    b.Property<string>("SN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Devices");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Device");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ERP_BIEN.Models.Hardware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HardDisk")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RAM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Hardware");
                });

            modelBuilder.Entity("ERP_BIEN.Models.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Asignada")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Caducidad")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("ERP_BIEN.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("ERP_BIEN.Models.PersonalInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Academy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FamilySituation")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<int?>("PreceptorDetailsId")
                        .HasColumnType("int");

                    b.Property<string>("Studies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeOfStudies")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreceptorDetailsId");

                    b.ToTable("PersonalInformation");
                });

            modelBuilder.Entity("ERP_BIEN.Models.PreceptorDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Disability")
                        .HasColumnType("bit");

                    b.Property<string>("GeographicMobility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIFCouple")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PreceptorDetails");
                });

            modelBuilder.Entity("ERP_BIEN.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ERP_BIEN.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("ERP_BIEN.Models.Software", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LicenseId")
                        .HasColumnType("int");

                    b.Property<string>("SO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId");

                    b.ToTable("Software");
                });

            modelBuilder.Entity("ERP_BIEN.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ProjectManagerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectManagerId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ERP_BIEN.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyInfoId")
                        .HasColumnType("int");

                    b.Property<string>("DomainUser")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PersonalInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyInfoId")
                        .IsUnique()
                        .HasFilter("[CompanyInfoId] IS NOT NULL");

                    b.HasIndex("PersonalInfoId")
                        .IsUnique()
                        .HasFilter("[PersonalInfoId] IS NOT NULL");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ERP_BIEN.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("ERP_BIEN.Models.Computer", b =>
                {
                    b.HasBaseType("ERP_BIEN.Models.Device");

                    b.Property<int>("ComputerType")
                        .HasColumnType("int");

                    b.Property<int?>("HardwareId")
                        .HasColumnType("int");

                    b.Property<int?>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<bool>("isClient")
                        .HasColumnType("bit");

                    b.HasIndex("HardwareId");

                    b.HasIndex("SoftwareId");

                    b.HasDiscriminator().HasValue("Computer");
                });

            modelBuilder.Entity("ERP_BIEN.Models.DockStation", b =>
                {
                    b.HasBaseType("ERP_BIEN.Models.Device");

                    b.HasDiscriminator().HasValue("DockStation");
                });

            modelBuilder.Entity("ERP_BIEN.Models.Phone", b =>
                {
                    b.HasBaseType("ERP_BIEN.Models.Device");

                    b.Property<int>("Extension")
                        .HasColumnType("int");

                    b.Property<int>("IMEI")
                        .HasColumnType("int");

                    b.Property<int>("PIN")
                        .HasColumnType("int");

                    b.Property<int>("PUK")
                        .HasColumnType("int");

                    b.Property<string>("SIM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("phonenumber")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Phone");
                });

            modelBuilder.Entity("ERP_BIEN.Models.Screen", b =>
                {
                    b.HasBaseType("ERP_BIEN.Models.Device");

                    b.Property<bool>("isTelework")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Screen");
                });

            modelBuilder.Entity("ERP_BIEN.Models.Ubikey", b =>
                {
                    b.HasBaseType("ERP_BIEN.Models.Device");

                    b.HasDiscriminator().HasValue("Ubikey");
                });

            modelBuilder.Entity("ERP_BIEN.Models.Ascendant", b =>
                {
                    b.HasOne("ERP_BIEN.Models.PersonalInformation", null)
                        .WithMany("Ascendants")
                        .HasForeignKey("PersonalInformationId");
                });

            modelBuilder.Entity("ERP_BIEN.Models.Child", b =>
                {
                    b.HasOne("ERP_BIEN.Models.PersonalInformation", null)
                        .WithMany("Childs")
                        .HasForeignKey("PersonalInformationId");
                });

            modelBuilder.Entity("ERP_BIEN.Models.Device", b =>
                {
                    b.HasOne("ERP_BIEN.Models.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP_BIEN.Models.License", b =>
                {
                    b.HasOne("ERP_BIEN.Models.User", "User")
                        .WithMany("Licenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP_BIEN.Models.PersonalInformation", b =>
                {
                    b.HasOne("ERP_BIEN.Models.PreceptorDetails", "PreceptorDetails")
                        .WithMany()
                        .HasForeignKey("PreceptorDetailsId");

                    b.Navigation("PreceptorDetails");
                });

            modelBuilder.Entity("ERP_BIEN.Models.RolePermission", b =>
                {
                    b.HasOne("ERP_BIEN.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP_BIEN.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ERP_BIEN.Models.Software", b =>
                {
                    b.HasOne("ERP_BIEN.Models.License", "Licenses")
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licenses");
                });

            modelBuilder.Entity("ERP_BIEN.Models.Team", b =>
                {
                    b.HasOne("ERP_BIEN.Models.User", "ProjectManager")
                        .WithMany("ManagedTeams")
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("ERP_BIEN.Models.User", b =>
                {
                    b.HasOne("ERP_BIEN.Models.CompanyInformation", "CompanyInfo")
                        .WithOne()
                        .HasForeignKey("ERP_BIEN.Models.User", "CompanyInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ERP_BIEN.Models.PersonalInformation", "PersonalInfo")
                        .WithOne()
                        .HasForeignKey("ERP_BIEN.Models.User", "PersonalInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ERP_BIEN.Models.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CompanyInfo");

                    b.Navigation("PersonalInfo");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ERP_BIEN.Models.UserRole", b =>
                {
                    b.HasOne("ERP_BIEN.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP_BIEN.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP_BIEN.Models.Computer", b =>
                {
                    b.HasOne("ERP_BIEN.Models.Hardware", "Hardware")
                        .WithMany()
                        .HasForeignKey("HardwareId");

                    b.HasOne("ERP_BIEN.Models.Software", "Software")
                        .WithMany()
                        .HasForeignKey("SoftwareId");

                    b.Navigation("Hardware");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("ERP_BIEN.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ERP_BIEN.Models.PersonalInformation", b =>
                {
                    b.Navigation("Ascendants");

                    b.Navigation("Childs");
                });

            modelBuilder.Entity("ERP_BIEN.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ERP_BIEN.Models.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("ERP_BIEN.Models.User", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Licenses");

                    b.Navigation("ManagedTeams");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
